//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCTD_indexer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCTD_indexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_document_open_icon_72x72 {
            get {
                object obj = ResourceManager.GetObject("Actions_document_open_icon_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_folder_new_icon_72x72 {
            get {
                object obj = ResourceManager.GetObject("Actions_folder_new_icon_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_system_run_icon_72x72 {
            get {
                object obj = ResourceManager.GetObject("Actions_system_run_icon_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_tab_close_other_icon_72x72 {
            get {
                object obj = ResourceManager.GetObject("Actions_tab_close_other_icon_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_view_refresh_icon_72x72 {
            get {
                object obj = ResourceManager.GetObject("Actions_view_refresh_icon_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Apps_kexi_icon_48x48 {
            get {
                object obj = ResourceManager.GetObject("Apps_kexi_icon_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--
        ///ectd
        ///util/ectd-2-0.xsl
        ///version 2.0
        ///transformation of the backbone from xml to html
        ///Yokohama, November 17, 2004
        ///--&gt;
        ///&lt;xsl:stylesheet  version=&quot;1.0&quot; 
        ///	xmlns:xsl = &quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:ectd = &quot;http://www.ich.org/ectd&quot;	
        ///	xmlns:xlink = &quot;http://www.w3c.org/1999/xlink&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;html&gt;
        ///			&lt;head&gt;
        ///				&lt;link rel=&quot;stylesheet&quot; href=&quot;util/style/screen.css&quot; type=&quot;text/css&quot; media=&quot;screen&quot;/&gt;
        ///			&lt;/head [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ectd_2_0 {
            get {
                return ResourceManager.GetString("ectd_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!--
        ///In the eCTD File Organisation: &quot;util/dtd/eu-envelope.mod&quot;
        ///
        ///Version 1.4
        ///August 2009
        ///
        ///Contributors:
        ///   AFSSAPS (Aziz Diop)
        ///   EMEA (Laurent Desqueper)
        ///   MEB (C.A. van Belkum)
        ///
        ///Version 2.0
        ///February 2013
        ///
        ///Contributors:
        ///EMA (Antonios Yfantis)
        ///
        ///Version 3.0
        ///October 2015
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)
        ///
        ///Version 3.0.1
        ///May 2016
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)--&gt;
        ///
        ///&lt;!-- ................................................................... --&gt;
        ///&lt;!ELEMENT eu-envelope (
        ///	envelope+ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string eu_envelope {
            get {
                return ResourceManager.GetString("eu_envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!--
        ///In the eCTD File Organisation: &quot;util/dtd/eu-leaf.mod&quot;
        ///
        ///Version 1.4
        ///August 2009
        ///
        ///Contributors:
        ///   ANSM (Aziz Diop)
        ///   EMA (Laurent Desqueper)
        ///   MEB (C.A. van Belkum)
        ///
        ///This is based on ich-ectd-3-2.dtd;
        ///
        ///If the ich-ectd.dtd is modularized, this one could be replaced.
        ///Hence, one is certain that the common and EU leaf are the same.
        ///--&gt;
        ///
        ///&lt;!-- ============================================================= --&gt;
        ///&lt;!ELEMENT node-extension (title, (leaf | node-extension)+)&gt;
        ///&lt;!ATTLIST node-extens [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string eu_leaf {
            get {
                return ResourceManager.GetString("eu_leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!--
        ///PUBLIC &quot;-//EU//DTD eCTD EU Backbone 3.0.1//EN&quot;
        ///In the eCTD File Organisation: &quot;util/dtd/eu-regional.dtd&quot;
        ///
        ///August 2009
        ///
        ///Contributors:
        ///ANSM (Aziz Diop)
        ///EMA (Laurent Desqueper)
        ///MEB (C.A. van Belkum)
        ///
        ///February 2013
        ///
        ///Contributors:
        ///EMA (Antonios Yfantis)
        ///
        ///June 2015
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)
        ///
        ///May 2016
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)
        ///
        ///Meaning or value of the suffixes:
        ///? : element must appear 0 or 1 time
        ///* : element must appear 0 or more time
        ///+ : element must appear 1  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string eu_regional {
            get {
                return ResourceManager.GetString("eu_regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!--
        ///	EU Module 1 Style-Sheet
        ///
        ///	Version 3.0.1
        ///	May 2016
        ///--&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;3.1&quot;
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:eu=&quot;http://europa.eu.int&quot; 
        ///	xmlns:xlink=&quot;http://www.w3c.org/1999/xlink&quot;&gt;
        ///   
        ///   &lt;xsl:output method=&quot;html&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot;/&gt;
        ///   
        ///   &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;html&gt;
        ///         &lt;head&gt;
        ///            &lt;title&gt;EU Module 1 - DTD version &lt;xsl:value-of select=&quot;/eu:eu-backbone/@dt [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string eu_regional1 {
            get {
                return ResourceManager.GetString("eu_regional1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Changes prior to Version 1.00 captured in file
        ///        &quot;Historical Changes.txt
        ///
        ///     ICH eCTD DTD
        ///     Version 1.0 - March 6, 2002
        ///     Version 3.0 - Sept 11, 2002
        ///     Version 3.0 - Oct 1, 2002
        ///     Version 3.0 - Oct 8, 2002
        ///     Version 3.1 - Nov 11, 2003
        ///	Version 3.2 - Nov 21, 2003
        ///
        ///Changes in version 3.1
        ///-	ID was changed to REQUIRED in the following four locations:
        ///		&lt;!ENTITY % att &quot; ID       ID     #REQUIRED
        ///             xml:lang CDATA  #IMPLIE [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ich_ectd_3_2 {
            get {
                return ResourceManager.GetString("ich_ectd_3_2", resourceCulture);
            }
        }
    }
}
