//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--
        ///ectd
        ///util/ectd-2-0.xsl
        ///version 2.0
        ///transformation of the backbone from xml to html
        ///Yokohama, November 17, 2004
        ///--&gt;
        ///&lt;xsl:stylesheet  version=&quot;1.0&quot; 
        ///	xmlns:xsl = &quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:ectd = &quot;http://www.ich.org/ectd&quot;	
        ///	xmlns:xlink = &quot;http://www.w3c.org/1999/xlink&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;html&gt;
        ///			&lt;head&gt;
        ///				&lt;link rel=&quot;stylesheet&quot; href=&quot;util/style/screen.css&quot; type=&quot;text/css&quot; media=&quot;screen&quot;/&gt;
        ///			&lt;/head [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ectd_2_0 {
            get {
                return ResourceManager.GetString("ectd_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///In the eCTD File Organisation: &quot;util/dtd/eu-envelope.mod&quot;
        ///
        ///Version 1.4
        ///August 2009
        ///
        ///Contributors:
        ///   AFSSAPS (Aziz Diop)
        ///   EMEA (Laurent Desqueper)
        ///   MEB (C.A. van Belkum)
        ///
        ///Version 2.0
        ///February 2013
        ///
        ///Contributors:
        ///EMA (Antonios Yfantis)
        ///
        ///Version 3.0
        ///October 2015
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)
        ///
        ///Version 3.0.1
        ///May 2016
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)--&gt;
        ///
        ///&lt;!-- ................................................................... --&gt;
        ///&lt;!ELEMENT eu-envelope (
        ///	envelope+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eu_envelope {
            get {
                return ResourceManager.GetString("eu_envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///In the eCTD File Organisation: &quot;util/dtd/eu-leaf.mod&quot;
        ///
        ///Version 1.4
        ///August 2009
        ///
        ///Contributors:
        ///   ANSM (Aziz Diop)
        ///   EMA (Laurent Desqueper)
        ///   MEB (C.A. van Belkum)
        ///
        ///This is based on ich-ectd-3-2.dtd;
        ///
        ///If the ich-ectd.dtd is modularized, this one could be replaced.
        ///Hence, one is certain that the common and EU leaf are the same.
        ///--&gt;
        ///
        ///&lt;!-- ============================================================= --&gt;
        ///&lt;!ELEMENT node-extension (title, (leaf | node-extension)+)&gt;
        ///&lt;!ATTLIST node-extens [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eu_leaf {
            get {
                return ResourceManager.GetString("eu_leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///PUBLIC &quot;-//EU//DTD eCTD EU Backbone 3.0.1//EN&quot;
        ///In the eCTD File Organisation: &quot;util/dtd/eu-regional.dtd&quot;
        ///
        ///August 2009
        ///
        ///Contributors:
        ///ANSM (Aziz Diop)
        ///EMA (Laurent Desqueper)
        ///MEB (C.A. van Belkum)
        ///
        ///February 2013
        ///
        ///Contributors:
        ///EMA (Antonios Yfantis)
        ///
        ///June 2015
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)
        ///
        ///May 2016
        ///
        ///Contributors:
        ///BFARM (Klaus Menges)
        ///
        ///Meaning or value of the suffixes:
        ///? : element must appear 0 or 1 time
        ///* : element must appear 0 or more time
        ///+ : element must appear 1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eu_regional {
            get {
                return ResourceManager.GetString("eu_regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot; standalone=&quot;no&quot;?&gt;
        ///
        ///&lt;!--
        ///	EU Module 1 Style-Sheet
        ///
        ///	Version 3.0.1
        ///	May 2016
        ///--&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;3.1&quot;
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:eu=&quot;http://europa.eu.int&quot; 
        ///	xmlns:xlink=&quot;http://www.w3c.org/1999/xlink&quot;&gt;
        ///   
        ///   &lt;xsl:output method=&quot;html&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot;/&gt;
        ///   
        ///   &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;html&gt;
        ///         &lt;head&gt;
        ///            &lt;title&gt;EU Module 1 - DTD version &lt;xsl:value-of select=&quot;/eu:eu-backbone/@dt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eu_regional1 {
            get {
                return ResourceManager.GetString("eu_regional1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Changes prior to Version 1.00 captured in file
        ///        &quot;Historical Changes.txt
        ///
        ///     ICH eCTD DTD
        ///     Version 1.0 - March 6, 2002
        ///     Version 3.0 - Sept 11, 2002
        ///     Version 3.0 - Oct 1, 2002
        ///     Version 3.0 - Oct 8, 2002
        ///     Version 3.1 - Nov 11, 2003
        ///	Version 3.2 - Nov 21, 2003
        ///
        ///Changes in version 3.1
        ///-	ID was changed to REQUIRED in the following four locations:
        ///		&lt;!ENTITY % att &quot; ID       ID     #REQUIRED
        ///             xml:lang CDATA  #IMPLIE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ich_ectd_3_2 {
            get {
                return ResourceManager.GetString("ich_ectd_3_2", resourceCulture);
            }
        }
    }
}
